### ISSUE TITLE
ItemToName.json内容咨询

### ISSUE THREAD

**Issue by zj65837** [ramoncjs3/HerosTime#4]
ItemToName.json，如何在游戏中获取数据，出很多新物品了不知道咋更新，目前提醒功能已经能用了

**Comment by ramoncjs3** [comment]
> ItemToName.json，如何在游戏中获取数据，出很多新物品了不知道咋更新，目前提醒功能已经能用了

ItemToName.json这个文件是单独处理过的，改起来稍微有些麻烦，我说下思路。
1. 你需要先抓包获取最新的物品接口，也就是item.json这个文件内容；
2. 然后再去抓包获取最新的物品描述的接口，它的key是item.json接口的value；
3. 抓到以上两个包的内容后，写个简单的脚本，做一个转换就行。
举例： 物品接口  :  {123:456}
物品描述接口 :   {456:丹药}
最终得到ItemToName.json内容 ：  {123:丹药}

**Comment by zj65837** [comment]
好的，感谢佬提供思路
